# Generated by Django 4.2.25 on 2025-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile_pictures/default_profile_pic.png', upload_to='profile_pictures/'),
        ),
    ]
