# Generated by Django 4.2.25 on 2025-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
