# Generated by Django 4.2.25 on 2025-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='30 minutes', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='static/course_thumbnails/download.jpg', upload_to='course_thumbnails/'),
        ),
    ]
