# Generated by Django 4.2.25 on 2025-11-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title_reward',
        ),
        migrations.AddField(
            model_name='course',
            name='reward_title',
            field=models.CharField(blank=True, help_text='Optional title to reward users after completing the course', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisite_courses', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='UserTitle',
        ),
    ]
