# Generated by Django 4.2.25 on 2025-11-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_title_reward_course_reward_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reward_title',
        ),
    ]
