# Generated by Django 4.2.25 on 2025-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_prerequisite_usertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_reward',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
