# Generated by Django 4.2.25 on 2025-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_title_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
